apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: validation-service
  description: Service for validating todo names and other inputs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guests
