apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springboot-service-template
  title: Spring Boot Service with Database
  description: A Spring Boot service template with PostgreSQL database support
  tags:
    - java
    - spring-boot
    - postgresql
    - rest-api
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Provide Service Information
      required:
        - serviceName
        - description
      properties:
        serviceName:
          title: Service Name
          type: string
          description: Unique name of the service (lowercase, no spaces)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A brief description of what this service does
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]

    - title: Database Configuration
      properties:
        databaseName:
          title: Database Name
          type: string
          description: Name of the PostgreSQL database
          default: servicedb
        databasePort:
          title: Database Port
          type: number
          description: PostgreSQL port
          default: 5432

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          serviceName: ${{ parameters.serviceName }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          databaseName: ${{ parameters.databaseName }}
          databasePort: ${{ parameters.databasePort }}
          packageName: com.example.${{ parameters.serviceName | replace("-", "") }}

    - id: publish
      name: Publish to Local Directory
      action: publish:local
      input:
        targetPath: services/${{ parameters.serviceName }}

  output:
    text:
      - title: Local Path
        content: Files created at ${{ steps['publish'].output.targetPath }}
      - title: Next Steps
        content: |
          Your service has been created successfully!

          To register it in the catalog, you can manually add the location:
          - Go to the Catalog page
          - Click "Register Existing Component"
          - Enter the file path: ${{ steps['publish'].output.targetPath }}/catalog-info.yaml
